### PR TITLE
setup a test for multicp upgrade

### PR DESCRIPTION
**Pull request by chuckha**
This test runs the upgrade against a 3 node control plane. it takes about 10 minutes to complete on an xl instance in aws.

`go test -count=1 -timeout 20m -v -run TestMultipleControlPlaneUpgradeScenario .`

code cleanups after idempotency work gets tested.

Signed-off-by: Chuck Ha <chuckh@vmware.com>

### CODE REVIEW

**Comment by ncdc** [comment]
LGTM but as we discussed on Slack, we could use `jsonpath` output using the `range/end` syntax instead of custom columns (to avoid having to skip the header line).

**Comment by chuckha** [comment]
Not sure if you missed https://github.com/vmware/cluster-api-upgrade-tool/pull/44/files#diff-53618cae32e23ae47e1c35f10da92654R160 or if you're asking me to remove that line in favor of jsonpath. Can you clarify what you'd like done and why? I don't see a benefit to deleting the `--no-header` and converting to jsonpath, but I want to hear your take

**Comment by ncdc** [comment]
Recording from Slack: my bad - missed the `--no-headers`.

Ready for me to merge?

**Comment by chuckha** [comment]
yes! go for it

**Pull request merged**
