### PR TITLE
Add a Dockerfile

### PR DESCRIPTION
**Pull request by williamsandrew**

### CODE REVIEW

**Comment by williamsandrew** [comment]
I just joined the VMware org for the CLA bot. May need to close/re-open the PR.

**Comment by chuckha** [comment]
I'd probably just close this and open a new PR against the same commit

**Comment by ncdc** [comment]
@williamsandrew let's just close this and open a new one, thanks.

**Comment by williamsandrew** [comment]
New PR here: https://github.com/vmware/cluster-api-upgrade-tool/pull/74

**Pull request closed without merging**
