### PR TITLE
Make CLI flags override config file values

### LINKED ISSUE #111: config file vs command line flags
with the addition of #104 we will be accepting config files in addition to command line flags.

It is a bit ambiguous how these two user supplied fields will interact with each other.

I suggest having the command line flags override the config file. The reason for this is that sometimes it's nice to use the same config with stuff I don't want to manually type in but override just a single field, such as version. Whatever the implementation, I'd like to avoid defining a complex precedence order.

### PR DESCRIPTION
**Pull request by ncdc**
Fixes #111

### CODE REVIEW

**Comment by chuckha** [comment]
Did you test this out?

**Comment by ncdc** [comment]
I did, although I'm wondering if maybe we should refactor `main.go` a bit to make this testable

**Comment by chuckha** [comment]
we could...i don't know if this logic is complex enough to warrant it though. i'd be more interested in putting that time to re building the e2e tests.

**Comment by ncdc** [comment]
SGTM! (I was mainly referring to the config merging part)

**Pull request merged**
