### PR TITLE
Flesh out makefile, test fixes, logic fixes

### PR DESCRIPTION
**Pull request by ncdc**
- Ensure go.mod/go.sum files are correct
- Add help descriptions to targets.
- Add targets for building the binary, docker image, releasing, updating go modules, verifying go modules, etc.

### CODE REVIEW

**Comment by vincepri** [comment]
Good old habits :)

**Comment by ncdc** [comment]
Fixed 2 broken tests (1 was due to some flawed logic waiting for a node with a matching provider id)

**Comment by ncdc** [comment]
Adding travis testing... https://travis-ci.org/vmware/cluster-api-upgrade-tool/builds/589636813

**Comment by ncdc** [comment]
@amy which PR do you want to merge first - yours or this one?

**Pull request merged**
