### PR TITLE
Add kubeadm configmap patching support

### LINKED ISSUE #144: The --bootstrap-patches option only changes the KubeadmConfig API but not Configmap in workload cluster
When supplying a set of JSON patches via the `--bootstrap-patches` option the KubeadmConfig API object in the management cluster is updated successfully. However, the Kubeadm configmap in the workload cluster is not changed which means said patches are effectively ignored. The only change that happens to the Kubeadm configmap is the `version` field which comes from this code: https://github.com/vmware/cluster-api-upgrade-tool/blob/0288bc748c450b487caceae130a9822df5d47a46/pkg/upgrade/control_plane.go#L204-L206.

To replicate, run the upgrade tool with a `--bootstrap-patches` option similar to this:

```
--bootstrap-patches=[{"op":"replace","path":"/spec/clusterConfiguration/dns/imageRepository","value":"example.com"},{"op":"replace","path":"/spec/clusterConfiguration/dns/imageTag","value":"some-tag"}]
```

Now review the KubeadmConfig API object for the upgraded machine as well as the Kubeadm Configmap in the workload cluster. You'll notice that only the former changed the DNS options.

### PR DESCRIPTION
**Pull request by ncdc**
Fixes #144

### CODE REVIEW

**Comment by ncdc** [comment]
@williamsandrew I picked your commit

**Comment by williamsandrew** [comment]
Do you want to me to adjust the commit message and re-pick since it has `WIP` in there?

**Comment by ncdc** [comment]
It's really up to you

**Comment by williamsandrew** [comment]
LGTM

**Pull request merged**
